//! Generated code: files a tool writes (GraphQL clients, protobuf, ORM
//! clients). They mirror a change made elsewhere, the schema or the
//! generator, so their contract rows read as one quiet row per component
//! that points at the source of the change.

use std::collections::{BTreeMap, BTreeSet};

use onus_core::{ChangeKind, ChangeLevel, Location, SemanticChange};

use crate::ctx::{Ctx, change, join_some, plural};
use crate::text::Status;

/// Whether `path` was written by a tool: by its name or folder, or by a
/// marker in its first lines (`@generated`, `DO NOT EDIT`, "This file was
/// generated").
pub fn is_generated(ctx: &Ctx, path: &str, status: Status) -> bool {
    let lower = path.to_ascii_lowercase();
    let name = lower.rsplit('/').next().unwrap_or(&lower);
    let dirs: Vec<&str> = lower.split('/').collect();
    if dirs[..dirs.len() - 1]
        .iter()
        .any(|d| matches!(*d, "generated" | "__generated__" | "codegen" | "gen-src"))
        || [".generated.", ".gen.", "_pb.", ".pb.", "_generated."]
            .iter()
            .any(|m| name.contains(m))
    {
        return true;
    }
    let root = if status == Status::Deleted {
        ctx.base_root
    } else {
        ctx.head_root
    };
    let Ok(text) = std::fs::read_to_string(onus_core::paths::native(root, path)) else {
        return false;
    };
    let head: String = text.lines().take(8).collect::<Vec<_>>().join("\n");
    let lower = head.to_ascii_lowercase();
    lower.contains("@generated")
        || lower.contains("do not edit")
        || lower.contains("auto-generated")
        || lower.contains("autogenerated")
        || lower.contains("code generated by")
        || lower.contains("this file was generated")
        || lower.contains("this file is generated")
        || lower.contains("this file was automatically generated")
}

/// Rows a generated file's change can produce that are better read once.
fn mergeable(r: &SemanticChange) -> bool {
    matches!(
        r.kind,
        ChangeKind::Additive | ChangeKind::Breaking | ChangeKind::Internal
    ) && !r.subkind.starts_with("route-")
        && r.subkind != "public-api-changed"
        && r.subkind != "secret-committed"
}

/// Folds rows whose locations all lie in generated files into one row per
/// component, and marks those files explained.
pub fn collapse(ctx: &Ctx, rows: Vec<SemanticChange>) -> Vec<SemanticChange> {
    let generated: BTreeSet<String> = ctx
        .text
        .files
        .iter()
        .filter(|f| is_generated(ctx, &f.path, f.status))
        .map(|f| f.path.clone())
        .collect();
    if generated.is_empty() {
        return rows;
    }
    let mut out = Vec::new();
    let mut by_component: BTreeMap<String, Vec<SemanticChange>> = BTreeMap::new();
    for r in rows {
        let all_generated =
            !r.locations.is_empty() && r.locations.iter().all(|l| generated.contains(&l.file));
        if all_generated && mergeable(&r) {
            let comp = ctx.component_of_path(&r.locations[0].file);
            by_component.entry(comp).or_default().push(r);
        } else {
            out.push(r);
        }
    }
    let mut files_by_component: BTreeMap<String, BTreeSet<&str>> = BTreeMap::new();
    for f in &generated {
        files_by_component
            .entry(ctx.component_of_path(f))
            .or_default()
            .insert(f.as_str());
        ctx.explain(f);
    }
    for (comp, files) in files_by_component {
        let members = by_component.remove(&comp).unwrap_or_default();
        let names: Vec<String> = files.iter().map(|f| format!("`{f}`")).collect();
        let place = if comp == "root" {
            "at the repository root".to_string()
        } else {
            format!("in `{comp}`")
        };
        let mut why = format!(
            "Written by a tool ({}); review the schema or generator change it mirrors",
            join_some(&names, 3)
        );
        if !members.is_empty() {
            let items: Vec<String> = members.iter().map(|m| m.title.clone()).collect();
            why.push_str(&format!("; it {}", lower_first(&join_some(&items, 4))));
        }
        let (added, removed) = ctx
            .text
            .files
            .iter()
            .filter(|f| files.contains(f.path.as_str()))
            .fold((0u32, 0u32), |(a, r), f| {
                let (fa, fr) = f.hunks.iter().fold((0, 0), |(a, r), h| {
                    (a + h.head_lines.len() as u32, r + h.base_lines.len() as u32)
                });
                (a + fa, r + fr)
            });
        let mut row = change(
            ChangeKind::Internal,
            "generated-code-changed",
            ChangeLevel::Structure,
            &comp,
            (comp != "root").then_some(comp.as_str()),
            "Generated code",
            format!(
                "Generated code changed {place} ({}, {})",
                plural(files.len() as u32, "file", "files"),
                plural(added + removed, "changed line", "changed lines")
            ),
            why,
            files.iter().map(|f| Location::head(*f, 1, 1)).collect(),
        );
        row.id = format!("generated-code-changed:{comp}");
        row.hints.blast_radius = members
            .iter()
            .map(|m| m.hints.blast_radius)
            .max()
            .unwrap_or(0);
        out.push(row);
    }
    // Rows in generated files of a component with no generated file left
    // (cannot happen, but never drop a row).
    out.extend(by_component.into_values().flatten());
    out
}

fn lower_first(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}
