#!/usr/bin/env bash
# Prints the Homebrew formula for an Onus release, from the release's
# SHA256SUMS. The release workflow pushes it to onushq/homebrew-tap; run it
# by hand to update the tap without the workflow:
#
#   scripts/homebrew-formula.sh v0.2.0 > ../homebrew-tap/Formula/onus.rb
#   scripts/homebrew-formula.sh v0.2.0 dist/SHA256SUMS   # a local SHA256SUMS
#
# Needs the GitHub CLI (logged in) unless a SHA256SUMS file is given.

set -euo pipefail

tag="${1:?usage: homebrew-formula.sh <tag> [SHA256SUMS]}"
sums_file="${2:-}"
version="${tag#v}"
repo="onushq/onus"

if [ -n "$sums_file" ]; then
  sums=$(cat "$sums_file")
else
  sums=$(gh release download "$tag" --repo "$repo" --pattern SHA256SUMS --output -)
fi

sha() {
  local want="onus-$1.tar.gz" s
  s=$(awk -v f="$want" '$2 == f || $2 == "*" f { print $1 }' <<< "$sums")
  if [ -z "$s" ]; then
    echo "homebrew-formula: no checksum for $want in SHA256SUMS" >&2
    exit 1
  fi
  printf '%s' "$s"
}

url="https://github.com/$repo/releases/download/$tag"

cat <<EOF
# Generated by scripts/homebrew-formula.sh in onushq/onus; do not edit by hand.
class Onus < Formula
  desc "Turns a pull request into a short report of changes in meaning"
  homepage "https://onushq.com"
  version "$version"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$url/onus-aarch64-apple-darwin.tar.gz"
      sha256 "$(sha aarch64-apple-darwin)"
    end
    on_intel do
      url "$url/onus-x86_64-apple-darwin.tar.gz"
      sha256 "$(sha x86_64-apple-darwin)"
    end
  end

  on_linux do
    on_arm do
      url "$url/onus-aarch64-unknown-linux-musl.tar.gz"
      sha256 "$(sha aarch64-unknown-linux-musl)"
    end
    on_intel do
      url "$url/onus-x86_64-unknown-linux-musl.tar.gz"
      sha256 "$(sha x86_64-unknown-linux-musl)"
    end
  end

  def install
    bin.install "onus", "onus-plugin-svelte"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/onus --version")
    (testpath/"pkg/package.json").write '{"name":"pkg","main":"index.ts"}'
    (testpath/"pkg/index.ts").write "export function hello(): string { return 'hi'; }\n"
    assert_match "1 symbols", shell_output("#{bin}/onus map #{testpath}/pkg")
  end
end
EOF
